[meta]
firstName = "Vidhi"
lastName = "Parekh"
role = "Software Developer"
about = """My career is developing software, but my life is adventuring. I am a curious person who enjoys figuring out the building blocks of the world, and rearranging them to build something even better. ¯\ (ツ) /¯

I’m passionate about building tools to help people save time and do more with their lives. I enjoy writing technical articles and research papers for a number of [publications](https://scholar.google.com/citations?user=IbedRsUAAAAJ&hl=en). You can read my articles at my [blog](https://vidhimody.me/hi/) where I write about software development, computer science, competitive coding, good coding practices and much more.

My goal is to travel the world with just one bag. When I’m not on a computer, I’m probably making pour-over coffee or practicing my zombie apocalypse skills, just not at the same time since shooting arrows through zombie heads makes maintaining a steady pour rate rather difficult."""

[meta.location]
city = "San Francisco"
country = "USA"
logo = "https://www.flaticon.com/free-icon/united-states_202950"

[[social]]
name = "github"
url = "https://github.com/vidhi-mody"
logo = "https://img.shields.io/github/followers/vidhi-mody?label=GitHub&style=social"

[[social]]
name = "linkedin"
url = "https://linkedin.com/in/vidhi-m"
logo = "https://img.shields.io/badge/Linkedin-grey?logo=linkedin&style=social"

[[social]]
name = "twitter"
url = "https://twitter.com/vidhi_mody"
logo = "https://img.shields.io/twitter/follow/vidhi_mody?label=Twitter&style=social"

[[projects]]
name = "Friend.ly"
url  = "https://github.com/und3fined-v01d/Friend.ly"
stars = "https://img.shields.io/github/stars/und3fined-v01d/Friend.ly?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/und3fined-v01d/Friend.ly?style=plastic&labelColor=343b41"

[[projects]]
name = "Apply By AI"
url = "https://github.com/vidhi-mody/Apply-By-AI"
stars = "https://img.shields.io/github/stars/vidhi-mody/Apply-By-AI?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/vidhi-mody/Apply-By-AI?style=plastic&labelColor=343b41"

[[projects]]
name = "Wanda Vision"
url = "https://github.com/vrushti-mody/WandaVision"
stars = "https://img.shields.io/github/stars/vrushti-mody/WandaVision?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/vrushti-mody/WandaVision?style=plastic&labelColor=343b41"

[[projects]]
name = "DSA"
url = "https://github.com/vidhi-mody/DSA"
stars = "https://img.shields.io/github/stars/vidhi-mody/DSA?style=plastic&labelColor=343b41"
forks = "https://img.shields.io/github/forks/vidhi-mody/DSA?style=plastic&labelColor=343b41"

[technologies]
python = "https://img.shields.io/badge/Python-black?logo=python&style=plastic"
go = "https://img.shields.io/badge/Go-black?logo=go&style=plastic"
java = "https://img.shields.io/badge/Java-black?logo=java&style=plastic"
javascript = "https://img.shields.io/badge/Javascript-black?logo=javascript&style=plastic"
typescript = "https://img.shields.io/badge/Typescript-black?logo=typescript&style=plastic"
npm = "https://img.shields.io/badge/npm-black?logo=npm&style=plastic"
nodejs = "https://img.shields.io/badge/Node.js-black?logo=node.js&style=plastic"
nestjs = "https://img.shields.io/badge/Nestjs-black?logo=nestjs&style=plastic"
angular = "https://img.shields.io/badge/Angular-black?logo=angular&style=plastic"
react = "https://img.shields.io/badge/React-black?logo=react&style=plastic"
django = "https://img.shields.io/badge/Django-black?logo=django&style=plastic"
php = "https://img.shields.io/badge/PHP-black?logo=php&style=plastic"
git = "https://img.shields.io/badge/Git-black?logo=git&style=plastic"
ansible = "https://img.shields.io/badge/Ansible-black?logo=ansible&style=plastic"
docker = "https://img.shields.io/badge/Docker-black?logo=docker&style=plastic"
kubernetes = "https://img.shields.io/badge/Kubernetes-black?logo=kubernetes&style=plastic"
github-actions = "https://img.shields.io/badge/Github%20Actions-black?logo=github-actions&style=plastic"
circleci = "https://img.shields.io/badge/CircleCI-black?logo=circleci&style=plastic"
vagrant = "https://img.shields.io/badge/Vagrant-black?logo=vagrant&style=plastic"
google-cloud-platform = "https://img.shields.io/badge/GCP-black?logo=google-cloud&style=plastic"
heroku = "https://img.shields.io/badge/Heroku-black?logo=heroku&style=plastic"
amazon-aws = "https://img.shields.io/badge/AWS-black?logo=amazon-aws&style=plastic"
numpy = "https://img.shields.io/badge/NumPy-black?logo=numpy&style=plastic"
pandas = "https://img.shields.io/badge/Pandas-black?logo=pandas&style=plastic"
scikit-learn = "https://img.shields.io/badge/Scikit%20Learn-black?logo=scikit-learn&style=plastic"
tensorflow = "https://img.shields.io/badge/Tensorflow-black?logo=tensorflow&style=plastic"
jest = "https://img.shields.io/badge/Jest-black?logo=jest&style=plastic"
cypress = "https://img.shields.io/badge/Cypress-black?logo=cypress&style=plastic"
selenium = "https://img.shields.io/badge/Selenium-black?logo=selenium&style=plastic"
elastic-stack = "https://img.shields.io/badge/Elastic%20Stack-black?logo=elastic-stack&style=plastic"
eslint = "https://img.shields.io/badge/ESLint-black?logo=eslint&style=plastic"
vscode = "https://img.shields.io/badge/VSCode-black?logo=visual-studio-code&style=plastic"
chrome = "https://img.shields.io/badge/Google%20Chrome-black?logo=google-chrome&style=plastic"
brave = "https://img.shields.io/badge/Brave-black?logo=brave&style=plastic"
duck-duck-go = "https://img.shields.io/badge/DuckDuckGo-black?logo=duckduckgo&style=plastic"
sass = "https://img.shields.io/badge/Sass-black?logo=sass&style=plastic"
styled-components = "https://img.shields.io/badge/Styled%20components-black?logo=styled-components&style=plastic"
